version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: harry@831just
      MYSQL_DATABASE: bookService
      MYSQL_USER: harry
      MYSQL_PASSWORD: harry@831just
    ports:
      - 3307:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_USER: harry
      DB_PASSWORD: harry@831just
      DB_NAME: bookService
    ports:
      - 3000:3000
